# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: retriever.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'retriever.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fretriever.proto\x12\tretriever\" \n\x0fRetrieveRequest\x12\r\n\x05query\x18\x01 \x01(\t\"J\n\x10RetrieveResponse\x12\x0e\n\x06\x61nswer\x18\x01 \x01(\t\x12&\n\tdocuments\x18\x02 \x03(\x0b\x32\x13.retriever.Document\"G\n\x08\x44ocument\x12\x14\n\x0cpage_content\x18\x01 \x01(\t\x12%\n\x08metadata\x18\x02 \x01(\x0b\x32\x13.retriever.Metadata\"?\n\x08Metadata\x12\r\n\x05sheet\x18\x01 \x01(\t\x12\x0f\n\x07row_idx\x18\x02 \x01(\t\x12\x13\n\x0btable_title\x18\x03 \x01(\t2W\n\x10RetrieverService\x12\x43\n\x08Retrieve\x12\x1a.retriever.RetrieveRequest\x1a\x1b.retriever.RetrieveResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'retriever_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RETRIEVEREQUEST']._serialized_start=30
  _globals['_RETRIEVEREQUEST']._serialized_end=62
  _globals['_RETRIEVERESPONSE']._serialized_start=64
  _globals['_RETRIEVERESPONSE']._serialized_end=138
  _globals['_DOCUMENT']._serialized_start=140
  _globals['_DOCUMENT']._serialized_end=211
  _globals['_METADATA']._serialized_start=213
  _globals['_METADATA']._serialized_end=276
  _globals['_RETRIEVERSERVICE']._serialized_start=278
  _globals['_RETRIEVERSERVICE']._serialized_end=365
# @@protoc_insertion_point(module_scope)
